### ISSUE TITLE
EngineController Class

### ISSUE THREAD

**Issue by ddfdfg** [SzFMV2020-Osz/AutomatedCar-B#46]
DoD:
- [ ] Issue #42 : EngineController class - CalculateDriveForce()

- [ ] Issue #43 : EngineController class - CalculateBrakeForce()

- [ ] Issue #44 : EngineController class - CalculateAcceleration()

- [ ] Issue #45 : EngineController class - CalculateVelocity()

- [x] Osztaly es alap propertyk letrehozas

**Comment by pintergreg** [comment]
Jó ez a gyűjtő issue, esetleg beszédesebbek is lehetnének a felsoroláspontok (tudom, hogy a elég link fölé vinni az egeret, de akkor is).
